title: Code Snippets
email: evokeapps@yahoo.com
description: >-
  Code snippets for programmers by programmers.
baseurl: ""
url: ""
twitter_username: evokeapps
github_username: evokeapps

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
